# -*- coding: utf-8 -*-
"""Major Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASbSEQCZSGQ1PEZOZjX8ov7pbj_rH6_B
"""

!pip install torch torchvision torchaudio
!pip install torch-geometric
!pip install pandas scikit-learn networkx

"""**Balanced Dataset Preparation**"""

import pandas as pd

df = pd.read_csv('URL dataset.csv')
df.head()

df.tail()

df.columns

df = df.rename(columns={
    df.columns[0] : 'url',
    df.columns[1] : 'label'
})

df.columns

df['label'].value_counts()

df['label'] = df['label'].map({
    'phishing' : 1,
    'legitimate' : 0
})

df['label'].value_counts()

df['url'].value_counts()

df.dropna(inplace=True) #removing null values
df['url'] = df['url'].str.lower().str.strip()
df.drop_duplicates(subset='url',inplace=True) #removing duplicates

df['url'].value_counts()

from numpy import random
phish = df[df.label==1]
legit = df[df.label==0]

min_size = min(len(phish),len(legit))

df_balanced = pd.concat([phish.sample(min_size,random_state=42),
                        legit.sample(min_size,random_state=42)])

df_balanced.to_csv('raw_urls.csv', index=False)

df = pd.read_csv('raw_urls.csv')
df.head()

df['label'].value_counts()

"""**URL Processing**"""

import re

def preprocess_url(url):
  url = url.lower()
  url = re.sub(r'https?://','',url)
  url = re.sub(r'www\.','',url)
  url = re.sub(r'[^a-z0-9./?=_-]','',url)
  return url
df['clean_url'] = df['url'].apply(preprocess_url)

df['clean_url']

print(df.shape)
print(df.head())

df['clean_url'][0]

"""**Feature Extraction**"""

#lexical features

import math
from collections import Counter

def lexical_features(url):
  length = len(url)
  special_chars = sum(not c.isalnum() for c in url)
  probability = [v/length for v in Counter(url).values()]
  entropy = -sum(p*math.log2(p) for p in probability if p > 0)
  return length,special_chars,entropy

lexical_features(df['clean_url'][1])

#structural features

from urllib.parse import urlparse

def structural_features(url):

  parsed = urlparse("https://" + url)
  sub_domains = parsed.netloc.count(".")
  path_depth = parsed.path.count("/")
  query_length = len(parsed.query)

  return sub_domains,path_depth,query_length

structural_features(df['clean_url'][0])

#statical features

def statistical_features(url):

  digits = sum(c.isdigit() for c in url)
  symbols = sum(not c.isalnum() for c in url)
  length = len(url)
  if length == 0:
      return 0, 0

  return digits/length,symbols/length

statistical_features(df['clean_url'][0])

import numpy as np

features = []

for url in df["clean_url"]:
    lex = lexical_features(url)
    struct = structural_features(url)
    stat = statistical_features(url)
    features.append(np.concatenate([lex, struct, stat]))

X = np.array(features)
y = df["label"].values

print("Feature shape:", X.shape)
print(X[0])

lex_features = []
struct_features = []
stat_features = []

for url in df["clean_url"]:
    lex_features.append(lexical_features(url))
    struct_features.append(structural_features(url))
    stat_features.append(statistical_features(url))
print(type(lex_features[0]))   # tuple/list
print(lex_features[0])         # numbers

"""**Dynamic Feature Fusion**"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class DynamicFeatureFusion(nn.Module):
    def __init__(self, lex_dim, struct_dim, stat_dim):
        super(DynamicFeatureFusion, self).__init__() #calls parent constructor

        # Learnable attention weights
        self.w_lex = nn.Parameter(torch.randn(lex_dim))
        self.w_struct = nn.Parameter(torch.randn(struct_dim))
        self.w_stat = nn.Parameter(torch.randn(stat_dim))

    def forward(self, lex, struct, stat):
        # Apply attention (element-wise multiplication)
        lex_att = lex * self.w_lex
        struct_att = struct * self.w_struct
        stat_att = stat * self.w_stat

        # Concatenate weighted features
        fused = torch.cat([lex_att, struct_att, stat_att], dim=1)
        return fused
# Convert NumPy features to Torch tensors
lex_features = torch.tensor(lex_features, dtype=torch.float)
struct_features = torch.tensor(struct_features, dtype=torch.float)
stat_features = torch.tensor(stat_features, dtype=torch.float)

#initiallize the model
fusion_model = DynamicFeatureFusion(
    lex_dim=3,
    struct_dim=3,
    stat_dim=2
)
#run the model
fused_features = fusion_model(
    lex_features,
    struct_features,
    stat_features
)

print("Fused feature shape:", fused_features.shape)

#normalizing fused features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
fused_features = torch.tensor(
    scaler.fit_transform(fused_features.detach().cpu().numpy()),
    dtype=torch.float
)

print(fused_features[0])

#comparision of before and after dynamic fusion
comparison = pd.DataFrame({
    "Lexical (before)": lex_features[:5].cpu().numpy().tolist(),
    "Structural (before)": struct_features[:5].cpu().numpy().tolist(),
    "Statistical (before)": stat_features[:5].cpu().numpy().tolist(),
    "Fused (after)": fused_features[:5].cpu().numpy().tolist()
})

comparison

"""**Hyper Graph Construction**"""

import random as py_random
from collections import defaultdict
import networkx as nx

def extract_domain(url):
    return url.split('/')[0]

df["domain"] = df["clean_url"].apply(extract_domain)

def extract_tokens(url, max_tokens=3):
    return set(
        url.replace('/', ' ')
           .replace('.', ' ')
           .split()[:max_tokens]
    )

df["tokens"] = df["clean_url"].apply(extract_tokens)


MAX_DOMAIN_EDGES = 6

G = nx.Graph()
num_nodes = len(df)
G.add_nodes_from(range(num_nodes))

domain_map = defaultdict(list)

for idx, domain in enumerate(df["domain"]):
    domain_map[domain].append(idx)

for nodes in domain_map.values():
    if len(nodes) > 1:
        for i in nodes:
            sampled = py_random.sample(
                nodes,
                min(MAX_DOMAIN_EDGES, len(nodes))
            )
            for j in sampled:
                if i != j:
                    G.add_edge(i, j)

MAX_TOKEN_EDGES = 6

token_map = defaultdict(list)

for idx, tokens in enumerate(df["tokens"]):
    for token in tokens:
        token_map[token].append(idx)

for nodes in token_map.values():
    if len(nodes) > 1:
        for i in nodes:
            sampled = py_random.sample(
                nodes,
                min(MAX_TOKEN_EDGES, len(nodes))
            )
            for j in sampled:
                if i != j:
                    G.add_edge(i, j)

print("Nodes:", G.number_of_nodes())
print("Edges:", G.number_of_edges())

"""**Visualization**"""

import matplotlib.pyplot as plt

# Pick one domain with many URLs
domain = df["domain"].value_counts().index[3]

domain_nodes = df[df["domain"] == domain].index.tolist()[:50]
domain_subG = G.subgraph(domain_nodes)

plt.figure(figsize=(8, 8))
pos = nx.spring_layout(domain_subG, seed=42)

nx.draw(
    domain_subG,
    pos,
    node_size=80,
    node_color="orange",
    edge_color="black",
    with_labels=False
)

plt.title(f"Hypergraph Subgraph (Domain: {domain})")
plt.show()

keyword = list(token_map.keys())[3]

keyword_nodes = token_map[keyword][:50]
keyword_subG = G.subgraph(keyword_nodes)

plt.figure(figsize=(8, 8))
pos = nx.spring_layout(keyword_subG, seed=42)

nx.draw(
    keyword_subG,
    pos,
    node_size=50,
    node_color="purple",
    edge_color="black",
    width=1.8,
    alpha=0.8,
    with_labels=False
)

plt.title("Keyword-based Hypergraph Subgraph (Edges Visible)")
plt.show()

"""**Graph Attention Network(GAT) + MLP**"""

import torch
import torch.nn.functional as F
from torch.nn import Linear, Dropout, BatchNorm1d
from torch_geometric.nn import GATConv
from torch_geometric.data import Data
from sklearn.metrics import accuracy_score, classification_report

print(type(G))
print(G.number_of_nodes(), G.number_of_edges())
edge_index = torch.tensor(
    list(G.edges),
    dtype=torch.long
).t().contiguous()

print(edge_index.shape)

import torch
from torch_geometric.data import Data

# Create PyG Data object
data = Data(
    x=fused_features,
    edge_index=edge_index,
    y=torch.tensor(df["label"].values, dtype=torch.long)
)

print(data)

num_nodes = data.num_nodes

# Split ratios
train_ratio = 0.7
val_ratio = 0.10
test_ratio = 0.20

# Calculate sizes
train_size = int(train_ratio * num_nodes)
val_size = int(val_ratio * num_nodes)

# Shuffle indices
indices = torch.randperm(num_nodes)

train_idx = indices[:train_size]
val_idx = indices[train_size:train_size + val_size]
test_idx = indices[train_size + val_size:]

# Create masks
train_mask = torch.zeros(num_nodes, dtype=torch.bool)
val_mask = torch.zeros(num_nodes, dtype=torch.bool)
test_mask = torch.zeros(num_nodes, dtype=torch.bool)

train_mask[train_idx] = True
val_mask[val_idx] = True
test_mask[test_idx] = True

# Assign masks to data
data.train_mask = train_mask
data.val_mask = val_mask
data.test_mask = test_mask

# Print statistics
print("Nodes:", data.num_nodes)
print("Edges:", data.num_edges)

print("Train nodes:", data.train_mask.sum().item())
print("Validation nodes:", data.val_mask.sum().item())
print("Test nodes:", data.test_mask.sum().item())

class GAT_MLP(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, heads=4, gat_conv_dropout=0.25, node_feature_dropout=0.3, mlp_dropout=0.3):
        super().__init__()

        # Store dropout rates
        self.node_feature_dropout = node_feature_dropout

        # First GAT Layer
        self.gat1 = GATConv(
            in_channels,
            hidden_channels,
            heads=heads,
            dropout=gat_conv_dropout # Dropout for attention coefficients
        )

        self.bn1 = BatchNorm1d(hidden_channels * heads)

        # Second GAT Layer
        self.gat2 = GATConv(
            hidden_channels * heads,
            hidden_channels,
            heads=1,
            concat=False,
            dropout=gat_conv_dropout # Dropout for attention coefficients
        )

        self.bn2 = BatchNorm1d(hidden_channels)

        # MLP classifier
        self.mlp = torch.nn.Sequential(
            Linear(hidden_channels, 128),
            torch.nn.ReLU(),
            Dropout(mlp_dropout), # Dropout within MLP
            Linear(128, out_channels)
        )

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        # GAT Layer 1
        x = self.gat1(x, edge_index)
        x = self.bn1(x)
        x = F.elu(x)
        x = F.dropout(x, p=self.node_feature_dropout, training=self.training) # Node feature dropout

        # GAT Layer 2
        x = self.gat2(x, edge_index)
        x = self.bn2(x)
        x = F.elu(x)

        # MLP
        x = self.mlp(x)

        return x

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = GAT_MLP(
    in_channels=data.x.shape[1],
    hidden_channels=64,
    out_channels=2
).to(device)

data = data.to(device)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=0.0004,
    weight_decay=1e-5
)

criterion = torch.nn.CrossEntropyLoss()

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='min',
    patience=10,
    factor=0.5
)

def train():
    model.train()
    optimizer.zero_grad()

    out = model(data)

    # Training loss
    train_loss = criterion(
        out[data.train_mask],
        data.y[data.train_mask]
    )

    train_loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), 2.0)
    optimizer.step()

    # Calculate training accuracy
    preds = out[data.train_mask].argmax(dim=1)
    correct = (preds == data.y[data.train_mask]).sum().item()
    total = data.train_mask.sum().item()
    train_acc = correct / total

    return train_loss.item(), train_acc

def validate():
    model.eval()
    with torch.no_grad():
        out = model(data)

        val_loss = criterion(
            out[data.val_mask],
            data.y[data.val_mask]
        )

        preds = out[data.val_mask].argmax(dim=1)
        correct = (preds == data.y[data.val_mask]).sum().item()
        total = data.val_mask.sum().item()
        val_acc = correct / total

    return val_loss.item(), val_acc

for epoch in range(1, 301):

    train_loss, train_acc = train()
    val_loss, val_acc = validate()

    scheduler.step(val_loss)

    if epoch % 10 == 0:
        print(f"Epoch {epoch:03d} | "
              f"Train Loss: {train_loss:.4f} | "
              f"Train Acc: {train_acc:.4f} | "
              f"Val Loss: {val_loss:.4f} | "
              f"Val Acc: {val_acc:.4f}")

def test():
    model.eval()
    with torch.no_grad():
        out = model(data)

        # Predictions for test set
        preds = out[data.test_mask].argmax(dim=1)

        y_true = data.y[data.test_mask]
        y_pred = preds

        # Accuracy
        correct = (y_pred == y_true).sum().item()
        total = data.test_mask.sum().item()
        acc = correct / total

    return acc, y_true.cpu(), y_pred.cpu()

acc, y_true, y_pred = test()

print("Final Accuracy:", acc)
print(classification_report(
    y_true,
    y_pred,
    target_names=["Legitimate", "Phishing"]
))

